--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Novembro-27-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_FORNECEDOR
--------------------------------------------------------

  CREATE TABLE "ROOT"."TB_FORNECEDOR" 
   (	"NOME" VARCHAR2(100 BYTE), 
	"CEP" NUMBER(*,0), 
	"RUA" VARCHAR2(100 BYTE), 
	"NUMERO" VARCHAR2(9 BYTE), 
	"COMPLEMENTO" VARCHAR2(100 BYTE), 
	"BAIRRO" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(100 BYTE), 
	"UF" VARCHAR2(2 BYTE), 
	"FONE1" NUMBER(11,0), 
	"FONE2" NUMBER(11,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"DT_CADASTRO" DATE, 
	"CNPJ_FORNECEDOR" VARCHAR2(14 BYTE), 
	"CONTATO" VARCHAR2(20 BYTE), 
	"OBSERVACAO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_PECA
--------------------------------------------------------

  CREATE TABLE "ROOT"."TB_PECA" 
   (	"NFISCAL" NUMBER(*,0), 
	"NOME" VARCHAR2(200 BYTE), 
	"VALOR" NUMBER(*,0), 
	"QTDE" NUMBER(*,0), 
	"CNPJ_FORNECEDOR" VARCHAR2(14 BYTE), 
	"COD_PECA" NUMBER(*,0), 
	"ID_OS" NUMBER, 
	"DATA_NF" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_SERVICO
--------------------------------------------------------

  CREATE TABLE "ROOT"."TB_SERVICO" 
   (	"DATA_SERVICO" DATE, 
	"DESCRICAO" VARCHAR2(400 BYTE), 
	"KM_SERVICO" NUMBER(*,0), 
	"PLACA" VARCHAR2(7 BYTE), 
	"ID_OS" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_VEICULO
--------------------------------------------------------

  CREATE TABLE "ROOT"."TB_VEICULO" 
   (	"PLACA" VARCHAR2(7 BYTE), 
	"MARCA" VARCHAR2(20 BYTE), 
	"MODELO" VARCHAR2(20 BYTE), 
	"ANO_FAB" VARCHAR2(4 BYTE), 
	"ANO_MOD" VARCHAR2(4 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROOT.TB_FORNECEDOR
SET DEFINE OFF;
Insert into ROOT.TB_FORNECEDOR (NOME,CEP,RUA,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,FONE1,FONE2,STATUS,DT_CADASTRO,CNPJ_FORNECEDOR,CONTATO,OBSERVACAO) values ('aaaaaaaaaaaa','11111111','aaaaaaaaaaa','1111','aaaaaaaaa','aaaaaaaa','aaaaaaa','aa','11111111111','22222222222','ATIVO',to_date('20/11/15','DD/MM/RR'),'11111111111111','aaaaaaaaa','aaaaaaaaaaaa');
Insert into ROOT.TB_FORNECEDOR (NOME,CEP,RUA,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,FONE1,FONE2,STATUS,DT_CADASTRO,CNPJ_FORNECEDOR,CONTATO,OBSERVACAO) values ('aaaaaaaaaaaa','11111111','aaaaaaaaaaa','1111','aaaaaaaaa','aaaaaaaa','aaaaaaa','aa','11111111111','22222222222','ATIVO',to_date('20/11/15','DD/MM/RR'),'33333333333333','aaaaaaaaa','aaaaaaaaaaaa');
Insert into ROOT.TB_FORNECEDOR (NOME,CEP,RUA,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,FONE1,FONE2,STATUS,DT_CADASTRO,CNPJ_FORNECEDOR,CONTATO,OBSERVACAO) values ('aaaaaaaaaaaa','11111111','aaaaaaaaaaa','1111','aaaaaaaaa','aaaaaaaa','aaaaaaa','aa','11111111111','22222222222','ATIVO',to_date('20/11/15','DD/MM/RR'),'22222222222222','aaaaaaaaa','aaaaaaaaaaaa');
Insert into ROOT.TB_FORNECEDOR (NOME,CEP,RUA,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,FONE1,FONE2,STATUS,DT_CADASTRO,CNPJ_FORNECEDOR,CONTATO,OBSERVACAO) values ('dddddddddddddddddddddddddd','11111111','aaaaaaaaaaa','1111','aaaaaaaaa','aaaaaaaa','aaaaaaa','aa','11111111111','22222222222','ATIVO',to_date('20/11/15','DD/MM/RR'),'44444444444444','aaaaaaaaa','aaaaaaaaaaaa');
REM INSERTING into ROOT.TB_PECA
SET DEFINE OFF;
REM INSERTING into ROOT.TB_SERVICO
SET DEFINE OFF;
Insert into ROOT.TB_SERVICO (DATA_SERVICO,DESCRICAO,KM_SERVICO,PLACA,ID_OS,STATUS) values (to_date('21/11/15','DD/MM/RR'),'serviço de mecanica','112000','CRY6568','1','ABERTA');
Insert into ROOT.TB_SERVICO (DATA_SERVICO,DESCRICAO,KM_SERVICO,PLACA,ID_OS,STATUS) values (to_date('21/01/15','DD/MM/RR'),'eletrica','100000','AAA1234','2','ABERTA');
Insert into ROOT.TB_SERVICO (DATA_SERVICO,DESCRICAO,KM_SERVICO,PLACA,ID_OS,STATUS) values (to_date('21/11/15','DD/MM/RR'),'eletrica','100000','AAA1234','3','ABERTA');
REM INSERTING into ROOT.TB_VEICULO
SET DEFINE OFF;
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('ddd0909','GM','corsa',null,null,'DISPONIVEL');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('dde0909','GM','corsa',null,null,'DISPONIVEL');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('CVP9040','VW','24250',null,null,'MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('DDX222','GM','CELTA',null,null,'MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('DDX2222','FIAT','PALIO',null,null,'MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('CRY6568','VW','16200','1999','2000','MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('CRU6568','GM','VECTRA',null,null,'MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('AAA1234','Iveco','240e25','2010','2011','MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('DDD0909','VW','16200',null,null,'MANUTENÇÃO');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('CCC1234','GM','CORSA SD',null,null,'DISPONIVEL');
Insert into ROOT.TB_VEICULO (PLACA,MARCA,MODELO,ANO_FAB,ANO_MOD,STATUS) values ('DDD1234','VW','16200',null,null,'DISPONIVEL');
--------------------------------------------------------
--  DDL for Index XPKTB_VEICULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."XPKTB_VEICULO" ON "ROOT"."TB_VEICULO" ("PLACA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKTB_PECA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."XPKTB_PECA" ON "ROOT"."TB_PECA" ("COD_PECA", "ID_OS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKTB_DESPESA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."XPKTB_DESPESA" ON "ROOT"."TB_SERVICO" ("PLACA", "DATA_SERVICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKTB_FORNECEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."XPKTB_FORNECEDOR" ON "ROOT"."TB_FORNECEDOR" ("CNPJ_FORNECEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_SERVICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."TB_SERVICO_PK" ON "ROOT"."TB_SERVICO" ("ID_OS", "PLACA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_PECA
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_PECA" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_PECA" MODIFY ("COD_PECA" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_PECA" MODIFY ("CNPJ_FORNECEDOR" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_PECA" ADD CONSTRAINT "XPKTB_PECA" PRIMARY KEY ("COD_PECA", "ID_OS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_FORNECEDOR
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_FORNECEDOR" ADD CONSTRAINT "XPKTB_FORNECEDOR" PRIMARY KEY ("CNPJ_FORNECEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."TB_FORNECEDOR" MODIFY ("CNPJ_FORNECEDOR" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_FORNECEDOR" MODIFY ("NOME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_VEICULO
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_VEICULO" ADD CONSTRAINT "XPKTB_VEICULO" PRIMARY KEY ("PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."TB_VEICULO" MODIFY ("PLACA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_SERVICO
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_SERVICO" ADD CONSTRAINT "TB_SERVICO_PK" PRIMARY KEY ("ID_OS", "PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."TB_SERVICO" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_SERVICO" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TB_SERVICO" MODIFY ("DATA_SERVICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TB_PECA
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_PECA" ADD CONSTRAINT "R_20" FOREIGN KEY ("CNPJ_FORNECEDOR")
	  REFERENCES "ROOT"."TB_FORNECEDOR" ("CNPJ_FORNECEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_SERVICO
--------------------------------------------------------

  ALTER TABLE "ROOT"."TB_SERVICO" ADD CONSTRAINT "R_21" FOREIGN KEY ("PLACA")
	  REFERENCES "ROOT"."TB_VEICULO" ("PLACA") ENABLE;
